on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

    # runs-on: ubuntu-latest
    # permissions:
    #   contents: read
    # steps:
    #   - uses: actions/checkout@v5

    #   - uses: denoland/setup-deno@v2
    #     with:
    #       cache: true

    #   - run: deno install

    #   - name: Audit
    #     run: deno task lint
  

  deal-link-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - uses: actions/checkout@v5

      - uses: AlexanderDokuchaev/md-dead-link-check@v1.3.0