on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  deal-link-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - uses: actions/checkout@v5

      - uses: AlexanderDokuchaev/md-dead-link-check@v1.3.0