on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5

      - uses: denoland/setup-deno@v2
        with:
          cache: true

      - run: deno install

      - name: Build
        run: deno task build
        env:
          TINA_CLIENT_ID: ${{ secrets.TINA_CLIENT_ID }}
          TINA_TOKEN: ${{ secrets.TINA_TOKEN }}

      - name: Deploy
        run: |
          deno deploy \
            --org=${{ vars.ORG }} \
            --app=${{ vars.APP }} \
            --token=${{ secrets.DENO_TOKEN }} \
            --prod \
            --no-wait \
